"""
Computer Thermal & Workload Model.

Models exactly 10 computers with CPU and GPU utilization, workload categories,
and synthetic heat dissipation.

DISCLAIMER: All computer heat values are purely SYNTHETIC simulation parameters
and must never be described or interpreted as measured real-world wattage.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Dict, List
import numpy as np

from generator.config import ComputerHeatConfig
from generator.models.room import COMPUTER_DEFINITIONS


class WorkloadCategory(str, Enum):
    IDLE = "IDLE"
    LIGHT = "LIGHT"
    GENERAL = "GENERAL"
    CPU_INTENSIVE = "CPU_INTENSIVE"
    GPU_INTENSIVE = "GPU_INTENSIVE"
    HEAVY = "HEAVY"


@dataclass
class ComputerState:
    id: str
    zone: str
    cpu_utilization_percent: float
    gpu_utilization_percent: float
    workload_category: WorkloadCategory
    simulated_heat_watts: float


class ComputerClusterModel:
    """Manages the 10 fixed computers in the room simulation."""

    def __init__(self, config: ComputerHeatConfig = None):
        self.config = config or ComputerHeatConfig()
        self.computers: Dict[str, ComputerState] = {}
        self._init_default_states()

    def _init_default_states(self):
        """Initialize all 10 computers to IDLE state."""
        for comp_id, info in COMPUTER_DEFINITIONS.items():
            self.computers[comp_id] = ComputerState(
                id=comp_id,
                zone=info["zone"],
                cpu_utilization_percent=5.0,
                gpu_utilization_percent=0.0,
                workload_category=WorkloadCategory.IDLE,
                simulated_heat_watts=self.calculate_heat_watts(5.0, 0.0),
            )

    def calculate_heat_watts(self, cpu_util: float, gpu_util: float) -> float:
        """Calculate synthetic computer heat from CPU and GPU utilization.

        Non-linear power scaling model:
        Heat = Base_Idle + Max_CPU * (cpu/100)^alpha + Max_GPU * (gpu/100)^beta
        """
        cpu_norm = max(0.0, min(100.0, cpu_util)) / 100.0
        gpu_norm = max(0.0, min(100.0, gpu_util)) / 100.0

        cpu_heat = self.config.max_cpu_watts * (cpu_norm ** self.config.cpu_exponent)
        gpu_heat = self.config.max_gpu_watts * (gpu_norm ** self.config.gpu_exponent)
        total_heat = self.config.base_idle_watts + cpu_heat + gpu_heat
        return float(round(total_heat, 2))

    def set_computer_state(
        self,
        comp_id: str,
        workload: WorkloadCategory,
        cpu_util: float,
        gpu_util: float,
    ):
        """Set specific utilization and workload for a computer."""
        if comp_id not in self.computers:
            raise KeyError(f"Invalid computer id: {comp_id}")

        zone = COMPUTER_DEFINITIONS[comp_id]["zone"]
        if isinstance(workload, str) and not isinstance(workload, WorkloadCategory):
            workload = WorkloadCategory(str(workload))
        elif hasattr(workload, "value") and not isinstance(workload, WorkloadCategory):
            workload = WorkloadCategory(workload.value)

        heat = self.calculate_heat_watts(cpu_util, gpu_util)
        self.computers[comp_id] = ComputerState(
            id=comp_id,
            zone=zone,
            cpu_utilization_percent=float(round(cpu_util, 2)),
            gpu_utilization_percent=float(round(gpu_util, 2)),
            workload_category=workload,
            simulated_heat_watts=heat,
        )

    def get_heat_by_zone(self) -> Dict[str, float]:
        """Aggregate total synthetic computer heat per thermal zone."""
        zone_heat = {"ZONE_1": 0.0, "ZONE_2": 0.0, "ZONE_3": 0.0, "ZONE_4": 0.0}
        for comp in self.computers.values():
            zone_heat[comp.zone] += comp.simulated_heat_watts
        return {z: round(w, 2) for z, w in zone_heat.items()}

    def get_total_heat_watts(self) -> float:
        """Total heat generated by all 10 computers."""
        return round(sum(comp.simulated_heat_watts for comp in self.computers.values()), 2)

    def step(self, rng: np.random.Generator, noise_std: float = 0.5):
        """Apply slight realistic temporal drift to CPU/GPU loads within their category."""
        for comp_id, state in self.computers.items():
            cat_key = state.workload_category.value if hasattr(state.workload_category, "value") else str(state.workload_category)
            min_c, max_c, min_g, max_g = self.config.workload_ranges[cat_key]
            new_cpu = float(np.clip(state.cpu_utilization_percent + rng.normal(0, noise_std), min_c, max_c))
            new_gpu = float(np.clip(state.gpu_utilization_percent + rng.normal(0, noise_std * 0.8), min_g, max_g))
            heat = self.calculate_heat_watts(new_cpu, new_gpu)

            self.computers[comp_id] = ComputerState(
                id=comp_id,
                zone=state.zone,
                cpu_utilization_percent=round(new_cpu, 2),
                gpu_utilization_percent=round(new_gpu, 2),
                workload_category=state.workload_category,
                simulated_heat_watts=heat,
            )
