"""
Occupancy Model.

Represents occupancy ONLY by zone counts. Does NOT create individual person objects.
Calculates occupancy heat per zone from counts using a configurable coefficient.
"""

from dataclasses import dataclass
from typing import Dict
import numpy as np

from generator.config import OccupancyConfig
from generator.models.room import ZONES


@dataclass
class OccupancyState:
    zone_1: int
    zone_2: int
    zone_3: int
    zone_4: int

    @property
    def total_occupancy(self) -> int:
        return self.zone_1 + self.zone_2 + self.zone_3 + self.zone_4

    def as_dict(self) -> Dict[str, int]:
        return {
            "ZONE_1": self.zone_1,
            "ZONE_2": self.zone_2,
            "ZONE_3": self.zone_3,
            "ZONE_4": self.zone_4,
        }


class OccupancyModel:
    """Manages zone occupancy counts and resulting sensible heat dissipation."""

    def __init__(self, config: OccupancyConfig = None):
        self.config = config or OccupancyConfig()
        self.state = OccupancyState(zone_1=0, zone_2=0, zone_3=0, zone_4=0)

    def set_occupancy(self, z1: int, z2: int, z3: int, z4: int):
        """Set zone occupancy counts directly."""
        self.state = OccupancyState(
            zone_1=max(0, int(z1)),
            zone_2=max(0, int(z2)),
            zone_3=max(0, int(z3)),
            zone_4=max(0, int(z4)),
        )

    def get_heat_by_zone(self) -> Dict[str, float]:
        """Calculates sensible heat dissipation in Watts for each zone.

        Q_occ = person_count * sensible_heat_per_person
        """
        counts = self.state.as_dict()
        coeff = self.config.sensible_heat_per_person_watts
        return {zone: round(counts[zone] * coeff, 2) for zone in ZONES}

    def get_total_heat_watts(self) -> float:
        """Total heat generated by all occupants across the room."""
        return round(self.state.total_occupancy * self.config.sensible_heat_per_person_watts, 2)
